### PR TITLE
CI/CD Rubocop Changes

### PR DESCRIPTION
**Pull request by kylanalewis**
PR includes new Rubocop (.rubocop.yml) file

1. Added Section and Class headers for files.
2. Excludes paths
    - 'db/**/*'
    - 'bin/*'
    - 'spec/feature/*'
    - 'config/environments/*'
    - 'config/initializers/devise.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

### CODE REVIEW

**Review by WRKirby — APPROVED** [review]
Fixes some automated testing issues we were having (CI/CD)

**Review by joycelingu — APPROVED** [review]
Fixed CI/CD

**Review by WRKirby — APPROVED** [review]
Helps the definition of done for almost all of our user stories by fixing up our tests.

**Review by joycelingu — APPROVED** [review]
Fixed CI/CD

**Pull request merged**
